name: Check for new PDFium releases

# on:
#   schedule:
#     # This will run at 00:00 every Saturday
#     - cron: '0 0 * * 6'

# on: workflow_dispatch
on: [push]

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Check for updates and create PR
      - name: Check for updates and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run check-updates
