name: Check for new PDFium releases

on:
  workflow_dispatch:
  schedule:
    # This will run at 10:00 every Saturday
    - cron: '0 10 * * 6'


jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Check for updates and create PR
      - name: Check for updates and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./scripts/check-updates.mjs
