name: Check for new PDFium releases

# on:
#   schedule:
#     # This will run at 00:00 every Saturday
#     - cron: '0 0 * * 6'

on: workflow_dispatch

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      # 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Check for updates and create PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: npm run check-updates
